version: '3.8'

services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - ./UI:/app
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend

  backend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3003:3000"
    volumes:
      - ./Middle:/app
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/n8n
      - N8N_URL=http://n8n:5678
    depends_on:
      - mongodb
      - n8n

  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      #- N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=development
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  n8n_data:
