services:
  gateway:
    image: middle_erp
    ports:
      - "3000:3000"
    env_file:
      - .env
  frontend:
    image: ui_erp
    ports:
      - "80:80"
    env_file:
      -.env
    depends_on:
      - gateway
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=user
      - N8N_BASIC_AUTH_PASSWORD=password
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=http://13.212.177.47:5678/
      - N8N_ENCRYPTION_KEY=super-secret-key
    depends_on:
      - db
    links:
      - mongodb
    restart: unless-stopped

  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - POSTGRES_DB=n8n
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    command: mongod
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongopasswd
    volumes:
      - mongo_storage_2:/data/db
    restart: always
    ports:
      - "27017:27017"
volumes:
  db-data:
  mongo_storage_2: