version: '3.8'

services:
  nocodb:
    image: nocodb/nocodb:latest
    container_name: noco
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./nocodb:/usr/app/data/
    environment:
      - NC_DB=pg://postgres:password@postgres:5432/nocodb
      - NC_AUTH_JWT_SECRET=569a1821-0a93-45e8-87ab-eb857f20a010
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres-nocodb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nocodb

volumes:
  postgres_data: