# Build stage
FROM node:18-alpine AS build
ARG VITE_GATEWAY_URL
ARG VITE_GOOGLE_CLIENT_ID
ENV VITE_GATEWAY_URL=$VITE_GATEWAY_URL
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
